export const restaurants = [{
    id: 1,
    title: "ASIA AROMAS",
    subTitle: "Chinese & Thai",
    img_url: '/imgs/dining/restaurant_logos/R1-DININGLOGO-Portrait.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R1-DININGLOGO-TEST4.png',
    phone: '+675 321 4780',
    address: 'Steamships Plaza, Downtown, Port Moresby',
    synopsis: `<p>Asia Aromas serves up a delicious blend of Thai and Chinese cuisine. Enjoy fine food, great service and spectacular views. <p></p>Open Monday to Saturday, 11am to 2pm and 5pm to 10pm, and Sunday 10.30pm to 2.30pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Chinese & Thai',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K16, Main: K30, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R1-Asia-Aromas-Map-01.png',
    images: [
        { imageFile: '/imgs/dining/R-Dining/R1-HeaderImages_P.jpg' }
    ],
    destination_id: 1

},
{
    id: 2,
    title: "CUPPA",
    subTitle: "Café Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R2-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/Cuppa_Cafe_Logo_FB.png',
    phone: '+675 302 8666',
    address: 'Shop G48, Vision City Megamall, 4027 Waigani, National Capital, Papua New Guinea',
    synopsis: `<p>Cuppa’s relaxed vibe offers the perfect place to catch up over great coffee. Enjoy refreshments such as Cuppa's big breakfasts, pasta, soup, sandwiches and more. <p></p>Open 7 days, 9am to 9pm. Free wifi available. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Café Cuisine',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K18, Main: K32, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R2-Cuppa-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R2-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 3,
    title: "HOSI RAMEN",
    subTitle: "Japanese",
    img_url: '/imgs/dining/restaurant_logos/R3-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R3-DININGLOGO-TEST4.png',
    phone: '+675 7662 8888',
    address: 'Vision City Waigani',
    synopsis: `<p>Tempt your taste buds at Hosi Ramen, a funky, upbeat Japanese noodle and sushi bar. Meander over for lunch or dinner. <p></p>Open 7 days a week, 11am to 9pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Japanese',
        takeaway: 'No',
        wifi: 'No',
        parking: 'No',
        courtesy: 'No',
        cards: '-',
        price: '-',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R3-Hosi-Ramen-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R3-HeaderImages_P.jpg' }     ],
    destination_id: 1

},
{
    id: 4,
    title: "HAPPY DUMPLINGS",
    subTitle: "Northern Chinese",
    img_url: '/imgs/dining/restaurant_logos/R5-DININGLOGO_P_EqWCjfj.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R5-DININGLOGO-TEST4.png',
    phone: '+675 302 8538',
    address: 'Vision City, Ground Floor, New Wing',
    synopsis: `<p>Famous for its Xiaolongbao traditional dumplings, Happy Dumplings is the place to be for northern style Dim Sum and Szechuan style dinner. <p></p>Open 7 days a week, Monday to Friday 11.00am to 2.00pm and 5.00pm to 10.00pm, and weekends 11.00am to 10.00pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Northern Chinese',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa',
        price: 'Entree: K25, Main: K70, Dessert: K26',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R4-Happy-Dumplings-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R4-HeaderImages_P.jpg' }     ],
    destination_id: 1

},
{
    id: 5,
    title: "KOREAN GARDENS",
    subTitle: "Korean Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R6-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R6-DININGLOGO_57MMTsQ.png',
    phone: '+675 302 8534 ',
    address: 'Vision City Waigani',
    synopsis: `<p>The traditional chef at Korean Gardens creates delicious, authentic Korean dishes. Enjoy a genuine Korean barbecue and stunning views from the restaurant. <p></p>Open 7 days a week, 11.00am to 2.00pm and 5.30pm to 10.00pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Korean Cuisine',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K22, Main: K48, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R5-Korean-Gardens-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R5-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 6,
    title: "YELLOW CAPTAIN PIZZA",
    subTitle: "Pizza & Pasta",
    img_url: '/imgs/dining/restaurant_logos/R7-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R7-DININGLOGO_NJ8qV8d.png',
    phone: '+675 302 8570',
    address: 'Vision City Mega Wall Waigani',
    synopsis: `<p>Yellow Captain Pizza, the pizza specialist, dishes up tasty pizzas, pasta and chicken dishes. Dine in or take away.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Pizza & Pasta',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa',
        price: 'Entree: K13, Main: K45, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R6-Yellow-Captain-Pizza-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R6-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 7,
    title: "HOG'S BREATH CAFÉ",
    subTitle: "Steak, Seafood, Australian",
    img_url: '/imgs/dining/restaurant_logos/R8-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R8-DININGLOGO_aLejlTs.png',
    phone: '+675 302 8550',
    address: 'Vision City Waigani',
    synopsis: `<p>There’s a Hog’s Breath Cafe in Port Moresby! Enjoy great steaks and a range of other delicious meals. Dine in or takeway. <p></p>Open daily, 11.30am to 10.00pm. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Steak, Seafood, Australian',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa, JBC',
        price: 'Entree: K32, Main: K68, Dessert: K22 ',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R7-Hog\'s-Breath-Cafe-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R7-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 8,
    title: "BEACHSIDE BRASSERIE",
    subTitle: "European Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R9-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R9-DININGLOGO_ooSDMZn.png',
    phone: '+675 321 2100',
    address: 'Ela Beach Hotel, Ela Beach Rd, Port Moresby',
    synopsis: `<p>Beachside Brasserie is located within the Ela Beach Hotel and showcases unique local art.  Enjoy a delicious blend of Pacific and international cuisine. <p></p>Open for breakfast, lunch and dinner.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'European Cuisine',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K18, Main: K30, Dessert: K22',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R8-Beachside-Brasserie-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R8-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 9,
    title: "CROWN HOTEL",
    subTitle: "Fine Dining",
    img_url: '/imgs/dining/restaurant_logos/Crowne_Hotel_Logo_P-01.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/Crowne_Hotel_Logo_P-01.jpg',
    phone: '+675 309 3000',
    address: 'Cnr Hunter & Douglas Streets, Port Moresby',
    synopsis: `<p>Crown Hotel offers a range of food and beverage options. Try any of these great venues for dining or relaxing and unwinding with a cocktail: The Café, The Heritage Bar, Rapala Restaurant and The Pondo Tavern. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Fine Dining',
        takeaway: 'No',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K48, Main: K91, Dessert: K35',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R9-Crown-Hotel-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R9-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 10,
    title: "DAIKOKU",
    subTitle: "Japanese Teppan-Yaki Steak House",
    img_url: '/imgs/dining/restaurant_logos/R11-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R11-DININGLOGO_FI4hY3y.png',
    phone: '+675 321 0255',
    address: 'Harbour City, Downtown, Port Moresby',
    synopsis: `<p>For a special place to dine, you can’t go past Daikoku. Boasting Japanese Teppan-yaki this is as much about the fabulous food as it is about the experience. The restaurant is Japanese owned so your experience is guaranteed to be an authentic one.</p>`,
    email: null,
    website: 'www.daikokupng.com/',
    guide: {
        cuisine: 'Japanese Teppan-Yaki Steak House',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa, JBC',
        price: 'Entree: K28, Main: K88, Dessert: K10',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R10-Daikoku-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R10-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 11,
    title: "DYNASTY SEAFOOD",
    subTitle: "Chinese, Malaysian & Yum Cha",
    img_url: '/imgs/dining/restaurant_logos/R12-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R12-DININGLOGO_2a03jKo.png',
    phone: '+675 302 8538',
    address: 'Vision City, Waigani Drive, Waigani',
    synopsis: `<p>Dine in at Dynasty Seafood and enjoy an extensive menu of fresh seafood blended with aromatic Asian herbs and spices. Yum Cha available every Saturday and Sunday for lunch. <p></p>Open Monday to Friday 11am to 2pm, and Saturday to Sunday 10.30am to 2pm and 5.30pm to 10pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Chinese, Malaysian & Yum Cha',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa, JBC',
        price: 'Entree: K20, Main: K30, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R11-Dynasty-Seafood-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R11- HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 12,
    title: "FU GUI VILLAGE RESTAURANT",
    subTitle: "Chinese & Malaysian",
    img_url: '/imgs/dining/restaurant_logos/R13-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R13-DININGLOGO_V8QDtk0.png',
    phone: '+675 323 0188',
    address: 'Gordons',
    synopsis: `<p>Fu Gui Village Restaurant is a family style eatery. Perfect for a relaxed night out. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Chinese & Malaysian',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K12, Main: K30, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R12-Fu-Gui-Village-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R12- HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 13,
    title: "FUSION BISTRO",
    subTitle: "Singaporean, Malaysian & Chinese",
    img_url: '/imgs/dining/restaurant_logos/R14-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R14-DININGLOGO_S8Bos9A.png',
    phone: '+675 7196 6666',
    address: 'Harbour City, Downtown, Port Moresby',
    synopsis: `<p>Excellent quality and service are all part of the Fusion experience. Combining Asian cuisine with a Western twist, you’re in for a fine dining treat whenever you visit Fusion. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Singaporean, Malaysian & Chinese',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K20, Main: K40, Dessert: K22 ',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R13-Fusion-Bistro-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R13- HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 14,
    title: "GATEWAY HOTEL",
    subTitle: "International Contemporary Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R15-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R15-DININGLOGO_GM5pROR.png',
    phone: '+675 327 8100',
    address: 'Jackson\'s Parade, Seven Mile',
    synopsis: `<p>Delight in the stylish ambience and signature gourmet pizzas at Jackson’s Restaurant, or cosy up with the family at Sizzler’s Family Restaurant. For takeaway, you can’t go past Enzo’s Express Takeaway. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'International Contemporary Cuisine',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes - To and from airport',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K30, Main: K60, Dessert: K30',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R14-Gateway-Hotel-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R14-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 15,
    title: "GRAND PALACE",
    subTitle: "Authentic Chinese & Malaysian",
    img_url: '/imgs/dining/restaurant_logos/R4-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R4-DININGLOGO_JMy6BZ8.png',
    phone: '+675 311 2826',
    address: '1st Floor, RH Hypermarket, Gordons',
    synopsis: `<p>Grand Palace Seafood Restaurant excels in authentic Chinese and Malaysian cuisine offering delicious Yum Cha every Saturday and Sunday. The restaurant caters for up to 250 people with ample parking. <p></p>Open daily, 11am to 2pm and 5.30pm to 10pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Authentic Chinese & Malaysian',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K15, Main: K28, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R15-Grand-Palace-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R15-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 16,
    title: "GRAND BRASSERIE",
    subTitle: "International Contemporary Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R17-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R17-DININGLOGO_10mUfpu.png',
    phone: '+675 304 0170',
    address: 'Grand Papua Hotel, Mary Street, Port Moresby',
    synopsis: `<p>The Grand Brasserie certainly makes a statement when it comes to quality and style. Overlooking Jackson's Harbour, this is the perfect place if you're seeking a fine dining experience. Blending Asian and Pacific Rim cuisine, the food here looks as good as it tastes. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'International Contemporary Cuisine',
        takeaway: 'No',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa ',
        price: 'Entree: K30, Main: K65, Dessert: K26 ',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R16-Grand-Brasserie-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R16-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 17,
    title: "GREEN HAUS RESTAURANT",
    subTitle: "International Contemporary Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R18-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R18-DININGLOGO_hhgJOqa.png',
    phone: '+675 302 8888',
    address: 'The Stanley Hotel',
    synopsis: `<p>Dine in the opulence of the Green Haus Restaurant located at the Stanley Hotel & Suite. Enjoy pastries, artisan bread and the fruity flavours of locally grown coffee. A buffet dinner finishes off the day with a sumptuous choice of cuisines. <p></p>Open for breakfast, lunch and dinner.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'International Contemporary Cuisine',
        takeaway: 'No',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K40, Main: K75 , Dessert: K40',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R17-Green-Haus-01.png',
    images: [  { imageFile: '/imgs/dining/R-Dining/R17-HeaderImage_P.jpg' },
        { imageFile: '/imgs/dining/R-Dining/R17-HeaderImage_P2.jpg' },
        { imageFile: '/imgs/dining/R-Dining/R17-HeaderImage_P3.jpg' }  ,
        { imageFile: '/imgs/dining/R-Dining/R17-HeaderImage_P4.jpg' }     
    ],
    destination_id: 1

},
{
    id: 18,
    title: "IMPERIAL CHINESE RESTAURANT",
    subTitle: "Authentic Chinese Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R19-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R19-DININGLOGO_I5lvJc8.png',
    phone: '+675 311 3668',
    address: 'Gabaka Street, Gordons',
    synopsis: `<p>Step up for some fabulous Oriental cuisine at Imperial Chinese Restaurant. <p></p>Open daily for lunch and dinner.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Authentic Chinese Cuisine',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa',
        price: 'Entree: K16, Main: K29, Dessert: K10',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R18-Imperial-Chinese-Restaurant-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R18-HeaderImage_P.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R18-HeaderImage_P2.jpg' }     ],
    destination_id: 1

},
{
    id: 19,
    title: "LAGUNA HOTEL",
    subTitle: "Asian & Western",
    img_url: '/imgs/dining/restaurant_logos/R20-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R20-DININGLOGO_qzIdpiI.png',
    phone: '+675 323 9333',
    address: 'Waigani Drive, Waigani',
    synopsis: `<p>Exuding a relaxed and intimate vibe, Laguna Café has a delicious array of food and beverages options available. <p></p>Open for breakfast, lunch and dinner, Laguna Café has all your needs covered.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Asian & Western',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'MC, Visa ',
        price: 'Entree: K20, Main: K50, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R19-Laguna-Hotel-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R19-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 20,
    title: "MAGI SEAFOOD RESTAURANT",
    subTitle: "Malaysian Chinese Seafood",
    img_url: '/imgs/dining/restaurant_logos/R21-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R21-DININGLOGO_81lSnoN.png',
    phone: '+675 323 3918',
    address: 'Spring Gardens Road, Gordons',
    synopsis: `<p>Magi Seafood Restaurant serves up an array of delectable and aromatic seafood dishes. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Malaysian Chinese Seafood',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'No',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K10, Main: K30, Dessert: K8',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R20-Magi-Seafood-Restaurant-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R20-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 21,
    title: "MR MIKES PIZZA",
    subTitle: "Pizza & Wings (Takeaway)",
    img_url: '/imgs/dining/restaurant_logos/R22-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R22-DININGLOGO_3PU2But.png',
    phone: '+675 343 1722',
    address: 'The Shady Rest Hotel, Taurama Road, Boroko',
    synopsis: `<p>If you enjoy gourmet pizzas at great value, you can’t go past Mr Mike’s Pizza. Offering a large range of thin crust pizzas, specialty wings, poutine and garlic bread, Mr Mike’s Pizza is open daily 10am to 10pm, and until 2am Friday and Saturday.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Pizza & Wings (Takeaway)',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'MC, Visa',
        price: 'Entree: K6, Main: K17',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R21-Mr-Mike\'s-Pizza-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R21-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 22,
    title: "PORT MORESBY NATURE PARK CAFÉ",
    subTitle: "Café Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R23-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R23-DININGLOGO_nrxbm6P.png',
    phone: '+675 326 0248',
    address: 'Goro Kaeaga Road, University',
    synopsis: `<p>For the curious and hungry visitor, Port Moresby Nature Park Café offers up a range of light refreshments and lunch options. <p></p>Open daily from 8.30am to 3.30pm. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Café Cuisine',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K12, Main: K20, Dessert: K10',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R22-Port-Moresby-NAture-Park-Cafe-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R22-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 23,
    title: "RAINFOREST CAFÉ",
    subTitle: "Café Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R24-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R24-DININGLOGO_8kfxykr.png',
    phone: '+675 302 8888',
    address: 'The Stanley Hotel',
    synopsis: `<p>Boasting an airy, light interior, the Rainforest Café is a casual yet stylish place to grab a snack or coffee. Kick back and relax or grab a homemade pastry on the go. <p></p>Open daily 6am to 6.30pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Café Cuisine',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa ',
        price: 'Entree: K20, Main: K45, Dessert: K20',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R23-Rainforest-Cafe-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R23-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 24,
    title: "SILVER LEAF RESTAURANT",
    subTitle: "Fine Dining",
    img_url: '/imgs/dining/restaurant_logos/R25-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R25-DININGLOGO_kHZuGjy.png',
    phone: '+675 302 8888',
    address: 'The Stanley Hotel',
    synopsis: `<p>If you’re seeking a fine dining experience, then look no further than Silver Leaf Restaurant. Boasting an opulent, modern interior, stunning views of Port Moresby complete this culinary experience where the quality of ingredients and flavours are unsurpassed.</p><p>Monday to Saturday 18:00 - 22:30 & Sunday: Closed</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Fine Dining',
        takeaway: 'No',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K50, Main: K95, Dessert: K50',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R24-Silver-Leaf-Restaurant-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R24-HeaderImage_P.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R24-HeaderImage_P2.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R24-HeaderImage_P3.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R24-HeaderImage_P4.jpg' }     ],
    destination_id: 1

},
{
    id: 25,
    title: "TANDOOR ON THE HARBOUR",
    subTitle: "Live Tandoor",
    img_url: '/imgs/dining/restaurant_logos/R26-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R26-DININGLOGO_qhwx7oH.png',
    phone: '+675 7172 3889',
    address: 'Pacific Palms Building, Granville, Downtown',
    synopsis: `<p>If aromatic cuisine and tasty flavours is your thing, then Tandoor on the Harbour is the choice for you. Specialising in Tandoor, this restaurant is known for its great curries and service. With views across the harbour, what more could you want?</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Live Tandoor',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K20, Main: K50, Dessert: K15',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R25-Tandoor-on-the-Harbour-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R25-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 26,
    title: "TASTY BITE",
    subTitle: "Indian & Tandoor",
    img_url: '/imgs/dining/restaurant_logos/R27-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R27-DININGLOGO_BwGVev3.png',
    phone: '+675 321 2222',
    address: 'Hunter Street, Port Moresby',
    synopsis: `<p>Tasty Bite brings you sumptuous Indian and Tandoor cuisine made by authentic Indian chefs. The food really is tasty so you won’t leave this establishment hungry. Large seating available or choose the private room for a more intimate setting. Excellent service guaranteed. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Indian & Tandoor',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K20, Main: K39, Dessert: K12',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R26-Tasty-Bite-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R26-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 27,
    title: "THE CELLAR RESTAURANT",
    subTitle: "Continental, Indian & Steak",
    img_url: '/imgs/dining/restaurant_logos/R28-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R28-DININGLOGO_FiAepOq.png',
    phone: '+675 323 0000',
    address: 'The Shady Rest Hotel, Taurama Road, Boroko',
    synopsis: `<p>Boasting an exciting array of Asian and continental cuisine, The Cellar Restaurant is the place to be. Famous for its dosa lunches and all you can eat Curry Club Buffet, the restaurant is also known for its excellent coffee.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Continental, Indian & Steak',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'Yes',
        cards: 'MC, Visa',
        price: 'Entree: K12, Main: K25, Dessert: K10',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R27-The-Cellar-Restaurant-01.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R27-HeaderImage_P.jpg' }     ],
    destination_id: 1

},
{
    id: 28,
    title: "LAE TRAVELLERS INN",
    subTitle: "Casual Dining, Western, Melanesian & Indian",
    img_url: '/imgs/dining/restaurant_logos/R29-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R29-DININGLOGO_CHlHuUN.png',
    phone: '+675 479 0411',
    address: 'Top Town, Vee Street next to Coronation College, Lae',
    synopsis: `<p>The Lae Travellers Inn offers a range of international cuisine at great prices in a relaxed environment.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Casual Dining, Western, Melanesian & Indian',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC, Visa',
        price: 'Entree: K8, Main: K30, Dessert: K11',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R28-Lea-Travellers-Inn.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R28-HeaderImage_P.jpg' }     ],
    destination_id: 2

},
{
    id: 29,
    title: "LAE INTERNATIONAL HOTEL",
    subTitle: "Fine dining, Brasserie & Pizza",
    img_url: '/imgs/dining/restaurant_logos/R30-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R30-DININGLOGO_OTTu7FH.png',
    phone: '+675 472 2000',
    address: '4th Street, Lae',
    synopsis: `<p>Located at the Lae International Hotel, the Vanda and Kokomo Restaurants serve up a tasty array of dishes inspired by Caribbean and international cuisine. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Fine dining, Brasserie & Pizza',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa',
        price: 'Entree: K35, Main: K49, Dessert: K35',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R29-Lea-International-Hotel.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R29-HeaderImage_P.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R29-HeaderImage_P2.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R29-HeaderImage_P3.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R29-HeaderImage_P4.jpg' }     ],
    destination_id: 2

},
{
    id: 30,
    title: "BUNGARAYA RESTAURANT",
    subTitle: "Malaysian & Chinese Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R31-DININGLOGO_p.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R31-DININGLOGO_nN77pyp.png',
    phone: '+675 472 7177',
    address: 'Lae Golf Club',
    synopsis: `<p>Bungaraya Restaurant will not disappoint with its traditional Chinese and Malay stir fries and hot plates. Keep an eye out for the lunchtime specials for great value. <p></p>Open daily, 11am to 2pm and 6pm to 10pm.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Malaysian & Chinese Cuisine',
        takeaway: 'Yes',
        wifi: 'No',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, Visa',
        price: 'Entree: K19, Main: K60, Dessert: K20',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R30-Bungaraya-Restaurant.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R30-HeaderImage_P.jpg' },
    { imageFile: '/imgs/dining/R-Dining/R30-HeaderImage_P2.jpg' }     ],
    destination_id: 2

},
{
    id: 31,
    title: "LAE CITY HOTEL",
    subTitle: "Western & Asian",
    img_url: '/imgs/dining/restaurant_logos/R32-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R32-DININGLOGO_eU1ZZI8.png',
    phone: '+675 472 0138',
    address: 'Third Street, Lae',
    synopsis: `<p>The City Café offers a blend of western and Asian cuisine in a relaxed setting. It’s worth visiting The City Café just for its signature dish, Tony’s Baby Back Ribs. </p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Western & Asian',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'Amex, MC, Visa ',
        price: 'Entree: K15, Main: K49, Dessert: K25',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R31-Lae-City-Hotel.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R31-HeaderImage_P.jpg' }     ],
    destination_id: 2

},
{
    id: 32,
    title: "THE GOLDEN AVIAT",
    subTitle: "Chinese Cuisine",
    img_url: '/imgs/dining/restaurant_logos/R33-DININGLOGO_P.jpg',
    imagesrc: '/imgs/dining/restaurant_logos/R33-DININGLOGO_upP9kod.png',
    phone: '+675 472 0486',
    address: 'Huon Road, Lae',
    synopsis: `<p>For anyone with a craving for Chinese food in Lae, the Golden Aviat is open daily for lunch and dinner. Swing by on Sundays for Yum Cha. Takeaway also available.</p>`,
    email: null,
    website: null,
    guide: {
        cuisine: 'Chinese Cuisine',
        takeaway: 'Yes',
        wifi: 'Yes',
        parking: 'Yes',
        courtesy: 'No',
        cards: 'MC',
        price: 'Entree: K5, Main: K50, Dessert: K15',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/R32-Golden-Aviat.png',
    images: [         { imageFile: '/imgs/dining/R-Dining/R32-HeaderImage_P.jpg' }     ],
    destination_id: 2

}/*,
{
    id: 33,
    title: "KIWA KOREAN RESTAURANT",
    subTitle: "Korean Cuisine",
    img_url: '/imgs/dining/restaurant_logos/XXX',
    imagesrc: '/imgs/dining/restaurant_logos/YYY',
    phone: '',
    address: '',
    synopsis: ``,
    email: null,
    website: null,
    guide: {
        cuisine: 'Korean Cuisine',
        takeaway: '',
        wifi: '',
        parking: '',
        courtesy: '',
        cards: '',
        price: '',
    },
    mapImage: '/imgs/dining/R-Dining/_Maps/xxxx'

}*/
];