import React from "react";
//import "../List/MainSectionList.css";
import {
    DECIMAL_RADIX,
    diningNamespace,
    imageGallery,
    HeavyOrange,
    LightBlueButtonBackground,
    ExtraHeavyBlueGreen,
    LightOrange
} from "../../../Constants";
import SidebarMapModel from "./../Maps/SidebarMapModel";
import { Link } from "react-router-dom";
import ActivityListIcon from "./icons/ActivityListIcon.png";
import "./Activity.scss";
import activityListIcon from '../../../components/MainContents/icons/ACTIVITIES_ICON.png';
import mapIcon from '../../../components/MainContents/icons/MapIcon.png';
import divingIcon from '../../../components/MainContents/icons/DIVING.svg';
import MapModal from "../Maps/MapModal";

class ActivityDestinationDetail1 extends React.Component {
    constructor(props) {
        super(props);

    }

    styles = {
        horizontalVerticalCenter: {
            display: "flex",
            justifyContent: "center"
        },
        slider: {
            height: "100%",
            duration: 10000,
            transitionDuration: 500,
            infinite: "true",
            indicators: "true",
            arrows: "true",
            onChange: (oldIndex, newIndex) => {
                console.log(`slide transition from ${oldIndex} to ${newIndex}`);
            }
        }
    };

    surfingList = [
        {
            id: 1,
            title: 'MADANG',
            img_url: '/imgs/activity/ACTIVITIES-SURFING.jpg',
            mapImage: './images/DIVING-Moresby-Map.png',
            overView: 'The northern side of PNG boasts some premier surfing locations with waves on the mainland and offshore islands generated by the monsoon swells from mid-October through to late April. Consistent quality waves.',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',

            }
        }, {
            id: 2,
            title: 'WEWAK',
            img_url: '/imgs/activity/ACTIVITIES-SURFING2.jpg',
            mapImage: './images/PNG-Map-TUFI.png',
            overView: 'Wewak is known for some great surf breaks, especially during October to April. During this time of the year, waves are consistently good ranging from three to eight feet and occasionally reaching ten feet. Pack your board. What are you waiting for?',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',
            }

        },
        {
            id: 3,
            title: 'PORT MORESBY',
            img_url: '/imgs/activity/ACTIVITIES-SURFING3.jpg',
            mapImage: './images/PNG-Map-TUFI.png',
            overView: 'During the south east season, the swell in the Port Moresby region ranges from three to six feet with the best waves served up early morning. Just fifteen minutes out from the nation’s capital heading south, you’ll discover a great surf break at Sero Cove. Pack your board for an action packed day of of surfing.',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',
            }

        },

    ];


    render() {
        const surfingDetail = this.surfingList[parseInt(this.props.match.params.id)]
        //   const { restaurant, status } = this.props;
        // const { divingList } = this.state;

        return (
            <div
                style={{
                    width: "100%",
                    height: "100%",
                    display: "flex",
                    color: "white"
                }}
                className="section--bottom--animation"
            >
                <div
                    style={{
                        backgroundColor: HeavyOrange,
                        width: "14%",
                        boxShadow: "9.899px 0px 7px 0px rgba(0,0,0,0.6)",
                        zIndex: 1,
                        display: "flex",
                        flexDirection: "column"
                    }}
                >
                    <Link
                        style={{
                            textDecoration: "none"
                        }}
                        to="/activities"
                    >
                        <div className="leftSide-menu--container">
                            <img
                                className="leftSide-menu--img"
                                src={activityListIcon}
                                alt="All ACTIVITIES Icon"
                            />
                            <div className="menu-title">All ACTIVITIES</div>
                        </div>
                    </Link>

                    {/* <SidebarMapModel
                        item={this.surfingList}
                        mainTitle="SURFING"
                        maps={this.surfingList.mapImage}
                        icon="./icons/ActivityListIcon.png"
                    /> */}
                    <Link
                        to="/activities/1"
                        style={{
                            textDecoration: "none"
                        }}

                    >
                        <div className="leftSide-menu--container">
                            <img
                                className="leftSide-menu--img"
                                src={mapIcon}
                                alt="DIVING MAP"
                            />
                            <div className="menu-title">SURFING MAP</div>
                        </div>
                    </Link>
                    <Link
                        to="/activities/1"
                        style={{
                            textDecoration: "none"
                        }}

                    >
                        <div className="leftSide-menu--container">
                            <img
                                className="leftSide-menu--img"
                                src={divingIcon}
                                alt="Diving Icon"
                            />
                            <div className="menu-title">SURFING AREAS</div>
                        </div>
                    </Link>
                    <div className="vertical-title">
                        <span style={{ transform: "rotate(-90deg)" }}>
                            ACTIVITIES
                        </span>
                    </div>
                </div>


                <div style={{ flex: 1, width: "86%", height: "54vh", backgroundColor: "rgb(5, 151, 165)" }}>

                    <div style={{ height: "40%" }}>
                        <div style={{ height: "100%", width: "100%" }} className="slide-container">
                            < img style={{ height: "100%", width: "100%" }} src={surfingDetail.img_url} />

                        </div>
                    </div>

                    <div className="activity-main-middle" style={{ height: "40%" }}>

                        <div
                            className="activity-main-middle--title"
                            style={{
                                //  height: "15%",
                                //  backgroundColor: LightOrange,

                                ...this.styles.horizontalVerticalCenter

                            }}
                        >
                            <span> DIVING</span>
                        </div>
                        <div className="activity-main-middle--subtitle">
                            <span>{surfingDetail.title}</span></div>
                        <div className="activity-main-middle--description">
                            <p>{surfingDetail.overView}</p>
                        </div>
                        <div className="activity-main-middle--moreInfo">
                            <span>FOR MORE INFORMATION CONTACT:</span></div>


                    </div>
                    <div className="activity-main-bottom">
                        <div className="activity-main-bottom--D1">
                            <div>
                                <span>{surfingDetail.associate.toUpperCase()}</span>

                            </div>
                            <div>
                                <span>{surfingDetail.details.phone}</span>
                                <span>{surfingDetail.details.website}</span>
                            </div>
                            <div>
                                <span>{surfingDetail.details.email}</span>
                            </div>
                        </div>

                    </div>
                </div >
            </div>
        );
    }

}
export default ActivityDestinationDetail1;
