import React from 'react';
import SubsectionList from "../List/SubsectionList";
import { DECIMAL_RADIX, activityNamespace } from '../../../Constants';
import activityListIcon from '../../../components/MainContents/icons/ACTIVITIES_ICON.png';
import mapIcon from '../../../components/MainContents/icons/MapIcon.png';

class ActivityDestinationList2 extends React.Component {
    surfingList = [
        {
            id: 1,
            title: 'MADANG',
            img_url: '/imgs/activity/ACTIVITIES-SURFING.jpg',
            mapActivity: './images/DIVING-Moresby-Map.png',
            overView: 'The northern side of PNG boasts some premier surfing locations with waves on the mainland and offshore islands generated by the monsoon swells from mid-October through to late April. Consistent quality waves.',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                Phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',

            }
        }, {
            id: 2,
            title: 'WEWAK',
            img_url: '/imgs/activity/ACTIVITIES-SURFING2.jpg',
            mapActivity: './images/PNG-Map-TUFI.png',
            overView: 'Wewak is known for some great surf breaks, especially during October to April. During this time of the year, waves are consistently good ranging from three to eight feet and occasionally reaching ten feet. Pack your board. What are you waiting for?',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                Phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',
            }

        },
        {
            id: 3,
            title: 'PORT MORESBY',
            img_url: '/imgs/activity/ACTIVITIES-SURFING3.jpg',
            mapActivity: './images/PNG-Map-TUFI.png',
            overView: 'During the south east season, the swell in the Port Moresby region ranges from three to six feet with the best waves served up early morning. Just fifteen minutes out from the nation’s capital heading south, you’ll discover a great surf break at Sero Cove. Pack your board for an action packed day of of surfing.',
            associate: 'SURFING ASSOCIATION OF PAPUA NEW GUINEA',
            details: {
                Phone: '+675 326 3999',
                email: 'sapng06@yahoo.com.au',
                website: 'www.sapng.com',
            }

        },

    ];

    render() {
        return (
            <div
                className="section--bottom--animation"
                style={{ width: "100%", height: "100%", color: "white" }}
            >
                <SubsectionList
                    numberOfEntries={4}
                    data={this.surfingList}
                    namespace={activityNamespace + "/2"}
                    //   namespace={namespace + "/id"}
                    imageKey="logo"
                    isImageArray={false}
                    sideButtons={[
                        { title: "ALL ACTIVITIES", icon: activityListIcon, isLink: true, link: activityNamespace },
                        { title: "SURFING MAP", icon: mapIcon, isMap: true }
                    ]}
                    sideTitle="SURFING"
                    mainTitle="SURFING"
                    maps={this.surfingList.mapActivity}
                >

                </SubsectionList>

            </div >
        );
    }
};
export default ActivityDestinationList2;
